-- Migration: Add context generation columns to verses table
-- Created: 2025-10-30
-- Description: Adds AI-generated context fields to support contextual explanations for verses

-- Add new columns to verses table
ALTER TABLE public.verses
  ADD COLUMN IF NOT EXISTS context TEXT,
  ADD COLUMN IF NOT EXISTS context_generated_by_ai BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS context_generated_at TIMESTAMPTZ;

-- Add index for querying verses without context (for batch processing)
CREATE INDEX IF NOT EXISTS idx_verses_missing_context
  ON public.verses (id)
  WHERE context IS NULL OR context = '';

-- Add index for querying AI-generated context
CREATE INDEX IF NOT EXISTS idx_verses_ai_context
  ON public.verses (context_generated_by_ai, context_generated_at)
  WHERE context_generated_by_ai = true;

-- Add comment for documentation
COMMENT ON COLUMN public.verses.context IS 'AI-generated spiritual context and explanation for the verse (1-3 sentences)';
COMMENT ON COLUMN public.verses.context_generated_by_ai IS 'Flag indicating whether context was generated by AI (true) or manually entered (false)';
COMMENT ON COLUMN public.verses.context_generated_at IS 'Timestamp when the context was generated';

-- Grant permissions (same as verses table)
GRANT SELECT ON public.verses TO anon, authenticated;
GRANT INSERT, UPDATE ON public.verses TO authenticated;
